name: Deploy to AWS

on:
  push:
    branches:
      - main # Triggers deployment on push to the 'main' branch. Modify as necessary.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Specify your Python version

      - name: Install AWS CLI
        run: |
          pip install awscli

      - name: Install EB CLI
        run: |
          pip install awsebcli  # Install Elastic Beanstalk CLI

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # Modify as per your region

      #      - name: Deploy to S3
      #        run: |
      #          aws s3 sync . s3://your-s3-bucket-name --exclude ".git/*" --exclude ".github/*"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Initialize Elastic Beanstalk
        run: |
          eb init -p python-3.9 emotion-recognition --region ap-south-1

      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy Emotion-recognition-qa --timeout 30
